matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      language: node_js
      node_js: '15'

    - os: linux
      dist: focal
      sudo: true
      language: node_js
      node_js: '15'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

script:
  - npm run dist
