# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Build and publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global url."https://github.com".insteadOf ssh://git@github.com
      - run: sudo apt install zlib1g-dev libpng-dev libxtst-dev libx11-dev  -y
      - run: npm install
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          xcode-version: latest-stable
      - run: git config --global url."https://github.com".insteadOf ssh://git@github.com
      - run: npm install
      - run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

