# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global url."https://github.com".insteadOf ssh://git@github.com
      - run: sudo apt install zlib1g-dev libpng-dev libxtst-dev libx11-dev  -y
      - run: npm install
      - run: npm run dist

  publish-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - run: git config --global url."https://github.com".insteadOf ssh://git@github.com
      - run: sudo apt install zlib1g-dev libpng-dev libxtst-dev libx11-dev  -y
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
